#!/bin/bash

# Path to your flags directory
FLAGS_DIR="./flags"

# Declare an associative array to map country codes to soccer abbreviations
declare -A country_map=(
    ["AF"]="AFG" ["AFG"]="AFG"
    ["DZ"]="ALG" ["DZA"]="ALG"
    ["AD"]="AND" ["AND"]="AND"
    ["AO"]="ANG" ["AGO"]="ANG"
    ["AG"]="ATG" ["ATG"]="ATG"
    ["AR"]="ARG" ["ARG"]="ARG"
    ["AM"]="ARM" ["ARM"]="ARM"
    ["AU"]="AUS" ["AUS"]="AUS"
    ["AZ"]="AZE" ["AZE"]="AZE"
    ["BS"]="BAH" ["BHS"]="BAH"
    ["BH"]="BHR" ["BHR"]="BHR"
    ["BD"]="BAN" ["BGD"]="BAN"
    ["BB"]="BRB" ["BRB"]="BRB"
    ["BY"]="BLR" ["BLR"]="BLR"
    ["BZ"]="BLZ" ["BLZ"]="BLZ"
    ["BJ"]="BEN" ["BEN"]="BEN"
    ["BT"]="BHU" ["BTN"]="BHU"
    ["BO"]="BOL" ["BOL"]="BOL"
    ["BA"]="BIH" ["BIH"]="BIH"
    ["BW"]="BWA" ["BWA"]="BWA"
    ["BR"]="BRA" ["BRA"]="BRA"
    ["BN"]="BRU" ["BRN"]="BRU"
    ["BG"]="BUL" ["BGR"]="BUL"
    ["BF"]="BFA" ["BFA"]="BFA"
    ["BI"]="BDI" ["BDI"]="BDI"
    ["KH"]="CAM" ["KHM"]="CAM"
    ["CM"]="CMR" ["CMR"]="CMR"
    ["CA"]="CAN" ["CAN"]="CAN"
    ["CV"]="CPV" ["CPV"]="CPV"
    ["CF"]="CAF" ["CAF"]="CAF"
    ["TD"]="CHA" ["TCD"]="CHA"
    ["CL"]="CHI" ["CHL"]="CHI"
    ["CN"]="CHN" ["CHN"]="CHN"
    ["CO"]="COL" ["COL"]="COL"
    ["KM"]="COM" ["COM"]="COM"
    ["CG"]="CGO" ["COG"]="CGO"
    ["CR"]="CRC" ["CRI"]="CRC"
    ["CU"]="CUB" ["CUB"]="CUB"
    ["CY"]="CYP" ["CYP"]="CYP"
    ["DJ"]="DJI" ["DJI"]="DJI"
    ["DM"]="DMA" ["DMA"]="DMA"
    ["DO"]="DOM" ["DOM"]="DOM"
    ["EC"]="ECU" ["ECU"]="ECU"
    ["EG"]="EGY" ["EGY"]="EGY"
    ["SV"]="SLV" ["SLV"]="SLV"
    ["GQ"]="GEQ" ["GNQ"]="GEQ"
    ["ER"]="ERI" ["ERI"]="ERI"
    ["EE"]="EST" ["EST"]="EST"
    ["SZ"]="SWZ" ["SWZ"]="SWZ"
    ["ET"]="ETH" ["ETH"]="ETH"
    ["FJ"]="FIJ" ["FJI"]="FIJ"
    ["FI"]="FIN" ["FIN"]="FIN"
    ["GA"]="GAB" ["GAB"]="GAB"
    ["GM"]="GAM" ["GMB"]="GAM"
    ["GH"]="GHA" ["GHA"]="GHA"
    ["GR"]="GRE" ["GRC"]="GRE"
    ["GD"]="GRN" ["GRD"]="GRN"
    ["GT"]="GUA" ["GTM"]="GUA"
    ["GN"]="GUI" ["GIN"]="GUI"
    ["GW"]="GNB" ["GNB"]="GNB"
    ["GY"]="GUY" ["GUY"]="GUY"
    ["HT"]="HAI" ["HTI"]="HAI"
    ["HN"]="HON" ["HND"]="HON"
    ["IS"]="ISL" ["ISL"]="ISL"
    ["IN"]="IND" ["IND"]="IND"
    ["ID"]="IDN" ["IDN"]="IDN"
    ["IR"]="IRN" ["IRN"]="IRN"
    ["IQ"]="IRQ" ["IRQ"]="IRQ"
    ["IE"]="IRL" ["IRL"]="IRL"
    ["IL"]="ISR" ["ISR"]="ISR"
    ["JM"]="JAM" ["JAM"]="JAM"
    ["JP"]="JPN" ["JPN"]="JPN"
    ["JO"]="JOR" ["JOR"]="JOR"
    ["KZ"]="KAZ" ["KAZ"]="KAZ"
    ["KE"]="KEN" ["KEN"]="KEN"
    ["KI"]="KIR" ["KIR"]="KIR"
    ["XK"]="KVX" ["KVX"]="KVX"
    ["KW"]="KUW" ["KWT"]="KUW"
    ["KG"]="KGZ" ["KGZ"]="KGZ"
    ["LA"]="LAO" ["LAO"]="LAO"
    ["LV"]="LVA" ["LVA"]="LVA"
    ["LB"]="LBN" ["LBN"]="LBN"
    ["LS"]="LES" ["LSO"]="LES"
    ["LR"]="LBR" ["LBR"]="LBR"
    ["LY"]="LBY" ["LBY"]="LBY"
    ["LI"]="LIE" ["LIE"]="LIE"
    ["LT"]="LTU" ["LTU"]="LTU"
    ["LU"]="LUX" ["LUX"]="LUX"
    ["MG"]="MAD" ["MDG"]="MAD"
    ["MW"]="MWI" ["MWI"]="MWI"
    ["MY"]="MAS" ["MYS"]="MAS"
    ["MV"]="MDV" ["MDV"]="MDV"
    ["ML"]="MLI" ["MLI"]="MLI"
    ["MT"]="MLT" ["MLT"]="MLT"
    ["MH"]="MHL" ["MHL"]="MHL"
    ["MR"]="MTN" ["MRT"]="MTN"
    ["MU"]="MRI" ["MUS"]="MRI"
    ["MX"]="MEX" ["MEX"]="MEX"
    ["FM"]="FSM" ["FSM"]="FSM"
    ["MD"]="MDA" ["MDA"]="MDA"
    ["MC"]="MON" ["MCO"]="MON"
    ["MN"]="MGL" ["MNG"]="MGL"
    ["ME"]="MNE" ["MNE"]="MNE"
    ["MA"]="MAR" ["MAR"]="MAR"
    ["MZ"]="MOZ" ["MOZ"]="MOZ"
    ["MM"]="MYA" ["MMR"]="MYA"
    ["NA"]="NAM" ["NAM"]="NAM"
    ["NR"]="NRU" ["NRU"]="NRU"
    ["NP"]="NEP" ["NPL"]="NEP"
    ["NZ"]="NZL" ["NZL"]="NZL"
    ["NI"]="NCA" ["NIC"]="NCA"
    ["NE"]="NIG" ["NER"]="NIG"
    ["NG"]="NGA" ["NGA"]="NGA"
    ["MK"]="MKD" ["MKD"]="MKD"
    ["NO"]="NOR" ["NOR"]="NOR"
    ["OM"]="OMA" ["OMN"]="OMA"
    ["PK"]="PAK" ["PAK"]="PAK"
    ["PW"]="PLW" ["PLW"]="PLW"
    ["PA"]="PAN" ["PAN"]="PAN"
    ["PG"]="PNG" ["PNG"]="PNG"
    ["PY"]="PAR" ["PRY"]="PAR"
    ["PE"]="PER" ["PER"]="PER"
    ["PH"]="PHI" ["PHL"]="PHI"
    ["QA"]="QAT" ["QAT"]="QAT"
    ["RU"]="RUS" ["RUS"]="RUS"
    ["RW"]="RWA" ["RWA"]="RWA"
    ["KN"]="SKN" ["KNA"]="SKN"
    ["LC"]="LCA" ["LCA"]="LCA"
    ["VC"]="VIN" ["VCT"]="VIN"
    ["WS"]="SAM" ["WSM"]="SAM"
    ["SM"]="SMR" ["SMR"]="SMR"
    ["ST"]="STP" ["STP"]="STP"
    ["SA"]="KSA" ["SAU"]="KSA"
    ["SN"]="SEN" ["SEN"]="SEN"
    ["SC"]="SEY" ["SYC"]="SEY"
    ["SL"]="SLE" ["SLE"]="SLE"
    ["SG"]="SIN" ["SGP"]="SIN"
    ["SB"]="SOL" ["SLB"]="SOL"
    ["SO"]="SOM" ["SOM"]="SOM"
    ["ZA"]="RSA" ["ZAF"]="RSA"
    ["KR"]="KOR" ["KOR"]="KOR"
    ["SS"]="SSD" ["SSD"]="SSD"
    ["LK"]="SRI" ["LKA"]="SRI"
    ["SD"]="SUD" ["SDN"]="SUD"
    ["SR"]="SUR" ["SUR"]="SUR"
    ["SE"]="SWE" ["SWE"]="SWE"
    ["SY"]="SYR" ["SYR"]="SYR"
    ["TW"]="TPE" ["TWN"]="TPE"
    ["TJ"]="TJK" ["TJK"]="TJK"
    ["TZ"]="TAN" ["TZA"]="TAN"
    ["TH"]="THA" ["THA"]="THA"
    ["TL"]="TLS" ["TLS"]="TLS"
    ["TG"]="TOG" ["TGO"]="TOG"
    ["TO"]="TGA" ["TON"]="TGA"
    ["TT"]="TTO" ["TTO"]="TTO"
    ["TN"]="TUN" ["TUN"]="TUN"
    ["TM"]="TKM" ["TKM"]="TKM"
    ["TV"]="TUV" ["TUV"]="TUV"
    ["UG"]="UGA" ["UGA"]="UGA"
    ["AE"]="UAE" ["ARE"]="UAE"
    ["GB"]="GBR" ["GBR"]="GBR"
    ["US"]="USA" ["USA"]="USA"
    ["UY"]="URU" ["URY"]="URU"
    ["UZ"]="UZB" ["UZB"]="UZB"
    ["VU"]="VAN" ["VUT"]="VAN"
    ["VA"]="VAT" ["VAT"]="VAT"
    ["VE"]="VEN" ["VEN"]="VEN"
    ["VN"]="VIE" ["VNM"]="VIE"
    ["YE"]="YEM" ["YEM"]="YEM"
    ["ZM"]="ZAM" ["ZMB"]="ZAM"
    ["ZW"]="ZIM" ["ZWE"]="ZIM"
    ["GB-WLS"]="WAL"
)

# Loop through each file in the directory
for file in "$FLAGS_DIR"/*; do
    # Extract the filename without the extension and convert it to uppercase
    filename=$(basename -- "$file")
    base_name="${filename%.*}"
    extension="${filename##*.}"

    # Convert the base name to uppercase
    upper_base_name=$(echo "$base_name" | tr '[:lower:]' '[:upper:]')

    # Check if the country code exists in the mapping array
    if [[ -n "${country_map[$upper_base_name]}" ]]; then
        new_filename="${country_map[$upper_base_name]}.${extension,,}"
        # Check if the new filename already exists
        if [ "$filename" != "$new_filename" ]; then
            if [ ! -f "$FLAGS_DIR/$new_filename" ]; then
                mv "$file" "$FLAGS_DIR/$new_filename"
                echo "Renamed $filename to $new_filename"
            else
                echo "File $new_filename already exists, skipping $filename"
            fi
        fi
    else
        echo "No mapping found for $filename, skipping"
    fi
done
